name: Build Vue App

on:
  release:
    types: [published]
    
jobs:
  build:
    name: Publish Vue App
    runs-on: ubuntu-latest
    permissions:
      contents: write
#       releases: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      - name: Install packages
        run: npm install
        
      - name: Build the app
        run: npm run build
        
      - name: Compress the dist folder # shouldn't we add the zip to ubuntu?
        run: zip -r dist.zip dist && ls -al
        
      - name: Upload dist to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist.zip
          asset_name: build.zip
          tag: ${{ github.ref }}

