name: Build Vue App

on:
  release:
    types: [published]
    
jobs:
  build:
    name: Build Vue App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # releases: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install packages
        run: npm install
        
      - name: Build the app
        run: npm run build
        
      - name: Compress the dist folder # shouldn't we add the zip to ubuntu?
        run: zip -r dist.zip dist
        
      - name: Upload dist to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist.zip
          asset_name: build.zip
