name: Minify Embedded HTML

on:
  push:
    paths:
      - 'embedded/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm ci
        
      - name: Minify HTML files
        run:  |
          for file in embedded/*.html; do
            npx html-minifier --input-dir embedded --output-dir embedded --file-ext html --output $file.min.html $file
          done
        #run: npx html-minifier --input-dir embedded --output-dir embedded
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions.github.com
          message: 'Minify embedded HTML files'
          add: 'embedded/*.min.html'
